

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findup-cpp.cmake")
# Global approach
set(up-cpp_FOUND 1)
set(up-cpp_VERSION "0.1")

find_package_handle_standard_args(up-cpp REQUIRED_VARS
                                  up-cpp_VERSION VERSION_VAR up-cpp_VERSION)
mark_as_advanced(up-cpp_FOUND up-cpp_VERSION)


set(up-cpp_INCLUDE_DIRS "/home/xz62px/.conan/data/up-cpp/0.1/_/_/package/4c9946599f8f5ae8a9212ddf357b51c461ef141b/include")
set(up-cpp_INCLUDE_DIR "/home/xz62px/.conan/data/up-cpp/0.1/_/_/package/4c9946599f8f5ae8a9212ddf357b51c461ef141b/include")
set(up-cpp_INCLUDES "/home/xz62px/.conan/data/up-cpp/0.1/_/_/package/4c9946599f8f5ae8a9212ddf357b51c461ef141b/include")
set(up-cpp_RES_DIRS )
set(up-cpp_DEFINITIONS )
set(up-cpp_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(up-cpp_COMPILE_DEFINITIONS )
set(up-cpp_COMPILE_OPTIONS_LIST "" "")
set(up-cpp_COMPILE_OPTIONS_C "")
set(up-cpp_COMPILE_OPTIONS_CXX "")
set(up-cpp_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(up-cpp_LIBRARIES "") # Will be filled later
set(up-cpp_LIBS "") # Same as up-cpp_LIBRARIES
set(up-cpp_SYSTEM_LIBS )
set(up-cpp_FRAMEWORK_DIRS )
set(up-cpp_FRAMEWORKS )
set(up-cpp_FRAMEWORKS_FOUND "") # Will be filled later
set(up-cpp_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(up-cpp_FRAMEWORKS_FOUND "${up-cpp_FRAMEWORKS}" "${up-cpp_FRAMEWORK_DIRS}")

mark_as_advanced(up-cpp_INCLUDE_DIRS
                 up-cpp_INCLUDE_DIR
                 up-cpp_INCLUDES
                 up-cpp_DEFINITIONS
                 up-cpp_LINKER_FLAGS_LIST
                 up-cpp_COMPILE_DEFINITIONS
                 up-cpp_COMPILE_OPTIONS_LIST
                 up-cpp_LIBRARIES
                 up-cpp_LIBS
                 up-cpp_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to up-cpp_LIBS and up-cpp_LIBRARY_LIST
set(up-cpp_LIBRARY_LIST up-cpp)
set(up-cpp_LIB_DIRS "/home/xz62px/.conan/data/up-cpp/0.1/_/_/package/4c9946599f8f5ae8a9212ddf357b51c461ef141b/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_up-cpp_DEPENDENCIES "${up-cpp_FRAMEWORKS_FOUND} ${up-cpp_SYSTEM_LIBS} spdlog::spdlog;fmt::fmt;GTest::GTest;protobuf::protobuf")

conan_package_library_targets("${up-cpp_LIBRARY_LIST}"  # libraries
                              "${up-cpp_LIB_DIRS}"      # package_libdir
                              "${_up-cpp_DEPENDENCIES}"  # deps
                              up-cpp_LIBRARIES            # out_libraries
                              up-cpp_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "up-cpp")                                      # package_name

set(up-cpp_LIBS ${up-cpp_LIBRARIES})

foreach(_FRAMEWORK ${up-cpp_FRAMEWORKS_FOUND})
    list(APPEND up-cpp_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND up-cpp_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${up-cpp_SYSTEM_LIBS})
    list(APPEND up-cpp_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND up-cpp_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(up-cpp_LIBRARIES_TARGETS "${up-cpp_LIBRARIES_TARGETS};spdlog::spdlog;fmt::fmt;GTest::GTest;protobuf::protobuf")
set(up-cpp_LIBRARIES "${up-cpp_LIBRARIES};spdlog::spdlog;fmt::fmt;GTest::GTest;protobuf::protobuf")

set(CMAKE_MODULE_PATH "/home/xz62px/.conan/data/up-cpp/0.1/_/_/package/4c9946599f8f5ae8a9212ddf357b51c461ef141b/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/xz62px/.conan/data/up-cpp/0.1/_/_/package/4c9946599f8f5ae8a9212ddf357b51c461ef141b/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET up-cpp::up-cpp)
        add_library(up-cpp::up-cpp INTERFACE IMPORTED)
        if(up-cpp_INCLUDE_DIRS)
            set_target_properties(up-cpp::up-cpp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${up-cpp_INCLUDE_DIRS}")
        endif()
        set_property(TARGET up-cpp::up-cpp PROPERTY INTERFACE_LINK_LIBRARIES
                     "${up-cpp_LIBRARIES_TARGETS};${up-cpp_LINKER_FLAGS_LIST}")
        set_property(TARGET up-cpp::up-cpp PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${up-cpp_COMPILE_DEFINITIONS})
        set_property(TARGET up-cpp::up-cpp PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${up-cpp_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT spdlog_FOUND)
            find_dependency(spdlog REQUIRED)
        else()
            message(STATUS "Dependency spdlog already found")
        endif()


        if(NOT fmt_FOUND)
            find_dependency(fmt REQUIRED)
        else()
            message(STATUS "Dependency fmt already found")
        endif()


        if(NOT GTest_FOUND)
            find_dependency(GTest REQUIRED)
        else()
            message(STATUS "Dependency GTest already found")
        endif()


        if(NOT Protobuf_FOUND)
            find_dependency(Protobuf REQUIRED)
        else()
            message(STATUS "Dependency Protobuf already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${up-cpp_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
